name: Сканирование Docker образа на уязвимости

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Тег образа alpine/openssl'
        required: false
        default: '3.3.3'
        type: string

jobs:
  scan:
    name: Проверка безопасности образа
    runs-on: ubuntu-latest
    
    steps:
      - name: Установка Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Сканирование образа
        run: |
          echo "Сканирование образа alpine/openssl:3.3.3"
          
          # Запускаем сканирование и сохраняем результаты
          trivy image \
            --severity HIGH,CRITICAL \
            --format table \
            --exit-code 1 \
            alpine/openssl:3.3.3 | tee scan_results.txt

      - name: Сохранение результатов
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: результаты-сканирования
          path: scan_results.txt
          retention-days: 7
