name: Сканирование Docker образа на уязвимости

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Тег образа alpine/openssl (latest по умолчанию)'
        required: false
        default: 'latest'
        type: string

jobs:
  scan:
    name: Проверка безопасности образа
    runs-on: ubuntu-latest
    
    steps:
      - name: Установка Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Сканирование образа alpine/openssl
        run: |
          echo "Начинаем проверку образа alpine/openssl:${{ inputs.image_tag }}"
          
          # Обновляем базу данных уязвимостей
          trivy image --download-db-only
          
          # Сканируем образ с расширенными параметрами
          trivy image \
            --severity HIGH,CRITICAL \
            --vuln-type os,library \
            --ignore-unfixed \
            --format table \
            --exit-code 1 \
            alpine/openssl:${{ inputs.image_tag }} | tee scan_results.txt

          # Сохраняем код выхода
          SCAN_EXIT_CODE=${PIPESTATUS[0]}
          
          # Выводим результаты
          echo "Результаты сканирования:"
          cat scan_results.txt
          
          # Проверяем наличие уязвимостей
          if [ $SCAN_EXIT_CODE -eq 1 ]; then
            echo "ВНИМАНИЕ: Обнаружены серьезные уязвимости!"
            exit 1
          else
            echo "Серьезных уязвимостей не обнаружено"
          fi

      - name: Сохранение результатов
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: результаты-сканирования
          path: scan_results.txt
          retention-days: 7

      - name: Итоговый отчет
        if: always()
        run: |
          echo "=== Подробный отчет о проверке ==="
          if [ -f scan_results.txt ]; then
            echo "Статистика уязвимостей:"
            cat scan_results.txt
          else
            echo "Ошибка: файл с результатами сканирования не найден"
          fi
